# Generated by Django 4.0.4 on 2022-07-19 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('WATER', 'WA'), ('GRASS', 'GR'), ('GHOST', 'GH'), ('STEEL', 'ST'), ('FAIRY', 'FA')], max_length=250),
        ),
    ]
