# Generated by Django 4.0.4 on 2022-07-19 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0002_alter_pokemon_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('GHOST', 'GH'), ('GRASS', 'GR'), ('FAIRY', 'FA'), ('STEEL', 'ST'), ('WATER', 'WA')], max_length=250),
        ),
    ]
